attempt to install to /usr/local/bin by default

diff --git a/tmux-config b/tmux-config
--- a/tmux-config
+++ b/tmux-config
@@ -2,10 +2,11 @@
 # shellcheck disable=SC2086
 
 # Initialization ----
-TMUX_CONFIG_PATH="$(cd "$(dirname "$0")"; pwd -P)/tmux-config"
 TMUX_VERSION="$(tmux -V | cut -d" " -f2)"
+TMUX_CONFIG_SOURCE="$(cd "$(dirname "$0")"; pwd -P)/tmux-config"
 
 # Configuration ----
+: ${TMUX_CONFIG_PATH="/usr/local/bin/tmux-config"}
 : ${TMUX_CONFIG_INPUT="${HOME}/.tmux/.tmux.conf"}
 : ${TMUX_CONFIG_OUTPUT="${HOME}/.tmux/config/$(uname)-${TMUX_VERSION}/.tmux.conf"}
 
@@ -17,6 +18,14 @@ if [ "$1" = "--bootstrap" ]; then
 	# Generated by tmux-config. Please edit the file at '${TMUX_CONFIG_INPUT/$HOME/\~}'.
 	run-shell "${TMUX_CONFIG_PATH}"
 	EOF
+
+	# copy the tmux configuration script to requested path
+	if [ ! -f "${TMUX_CONFIG_PATH}" ]; then
+		cp "${TMUX_CONFIG_SOURCE}" "${TMUX_CONFIG_PATH}" || {
+			echo "Failed to copy tmux-config to '${TMUX_CONFIG_PATH}'"
+			exit 1
+		}
+	fi
 
 	# if it looks like we've never added an autoloader, this is likely the
 	# user's own '.tmux.conf' file
